#!/bin/bash

app="pacman-mirrors $*"

if [ `id -u` -eq 0 ]; then
	#user is admin
	${app}
else
	#user is not admin
	if `echo $- | grep "i" >/dev/null 2>&1`; then
		#script is running in interactive mode
		su - -c "${app}"
	else
		#script is running in non-interactive mode
		if [ $XDG_SESSION_TYPE = "wayland" ] ; then
			xhost +SI:localuser:root
			pkexec ${app}
			xhost -SI:localuser:root
			xhost
		elif command -v pkexec >/dev/null 2>&1; then
			pkexec env DISPLAY=$DISPLAY XAUTHORITY=$XAUTHORITY ${app}
		elif command -v sudo >/dev/null 2>&1; then
			x-terminal-emulator -e "sudo ${app}"
		elif command -v su >/dev/null 2>&1; then
			x-terminal-emulator -e "su - -c '${app}'"
		else
			x-terminal-emulator -e "echo 'Command must be run as root user: ${app}'"
		fi
	fi
fi
