#!/usr/bin/env python
# -*- coding: utf-8 -*-
#
# This file is part of pacman-mirrors.
#
# pacman-mirrors is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# pacman-mirrors is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with pacman-mirrors.  If not, see <http://www.gnu.org/licenses/>.
#
# Author(s): Ramon Buldó <rbuldo@gmail.com>

import os
from pacman_mirrors import pacman_mirrors
from pacman_mirrors import i18n

_ = i18n.language.gettext

if os.getuid() != 0:
    print(_("Error: must have root privilegies."))
    exit(1)

try:
    pm = pacman_mirrors.PacmanMirrors()
    pm.run()
except KeyboardInterrupt:
    print(_("\nError: interrupted by the user."))
    exit(1)

